import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { notFound, redirect } from "next/navigation";
import { MonitoringControls } from "./monitoring-controls";
import { WordPressControl } from "./wordpress-control";

export default async function BusinessPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const { id } = await params;
  const business = await prisma.business.findFirst({ where: { id, userId: user.id }, include: { scans: { orderBy: { createdAt: "desc" }, take: 12 }, opportunities: { where: { status: "open" }, orderBy: { impact: "desc" }, take: 12 }, actions: { orderBy: { createdAt: "desc" }, take: 20 }, connectors: { select: { type: true, status: true, baseUrl: true } }, monitoredQueries: { orderBy: { updatedAt: "desc" }, take: 20 }, monitoringRuns: { orderBy: { startedAt: "desc" }, take: 10 } } });
  if (!business) notFound();
  const delta = business.scans.length > 1 ? business.scans[0].score - business.scans[1].score : 0;
  return <main className="shell"><header className="topbar"><div><a href="/dashboard" className="muted">← Dashboard</a><h1>{business.name}</h1><p className="muted">{business.url}</p></div><div style={{display:"flex",gap:8}}><a className="ghost" href={`/business/${business.id}/history`}>Historique</a><a className="ghost" href={`/business/${business.id}/activity`}>Journal</a><a className="ghost" href={`/business/${business.id}/intelligence`}>Intelligence</a><a className="primary inline" href="/scan">Rescanner</a></div></header>
    <section className="grid-4"><div className="metric"><span>Score</span><strong>{business.score}</strong><small>Readiness Score</small></div><div className="metric"><span>Évolution</span><strong>{delta >= 0 ? "+" : ""}{delta}</strong><small>depuis le scan précédent</small></div><div className="metric"><span>Actions</span><strong>{business.actions.filter(a=>a.status!=="rolled_back").length}</strong><small>proposées / appliquées</small></div><div className="metric"><span>Monitoring</span><strong>{business.monitoring ? "ON" : "OFF"}</strong><small>{business.nextMonitorAt ? new Date(business.nextMonitorAt).toLocaleString("fr-FR") : "non planifié"}</small></div></section>
    <section className="two-col"><div className="panel"><div className="panel-head"><h2>Autopilot</h2><span className="badge">{business.monitoring ? "actif" : "manuel"}</span></div><p className="muted">SignalPilot rescannera le site, suivra les requêtes et générera de nouvelles actions lorsque le monitoring est actif.</p><MonitoringControls id={business.id} enabled={business.monitoring} everyHours={business.monitorEveryHours} /></div>
    <div className="panel"><div className="panel-head"><h2>WordPress</h2><span className="badge">{business.connectors.some(c=>c.type==="wordpress" && c.status==="connected") ? "connecté" : "non connecté"}</span></div><p className="muted">Le connecteur est préparé pour les modifications contrôlées avec snapshot et rollback.</p><p className="small">Connexion : POST /api/business/{business.id}/connector</p></div></section>
    <WordPressControl businessId={business.id} connected={business.connectors.some(c=>c.type==="wordpress" && c.status==="connected")} baseUrl={business.connectors.find(c=>c.type==="wordpress")?.baseUrl} />
    <section className="panel"><div className="panel-head"><div><h2>Actions</h2><p className="muted">Préparer, publier et restaurer des modifications contrôlées.</p></div><a href={`/business/${business.id}/activity`}>Voir le journal →</a><span className="badge">{business.actions.length}</span></div>{business.actions.length ? business.actions.map(a=><div className="op" key={a.id}><div><strong>{a.title}</strong><p>{a.description}</p><small>{a.type} · {a.status}</small></div><span>{a.status}</span></div>) : <p className="muted">Aucune action pour le moment. Lancez un scan.</p>}</section>
    <section className="two-col"><div className="panel"><div className="panel-head"><h2>Requêtes surveillées</h2></div>{business.monitoredQueries.length ? business.monitoredQueries.map(q=><div className="row" key={q.id}><span>{q.query}</span><strong>{q.lastMentioned ? "Mention" : q.lastRunAt ? "Non mentionné" : "En attente"}</strong></div>) : <p className="muted">Les requêtes apparaîtront au prochain monitoring.</p>}</div><div className="panel"><div className="panel-head"><h2>Historique monitoring</h2></div>{business.monitoringRuns.map(r=><div className="row" key={r.id}><span>{new Date(r.startedAt).toLocaleString("fr-FR")}</span><strong>{r.status === "completed" ? `${r.delta && r.delta>0?"+":""}${r.delta ?? 0}` : r.status}</strong></div>)}</div></section>
  </main>;
}
