"use client";
import { useEffect, useState } from "react";

type Item = { id:number; status?:string; link?:string; title?:{rendered?:string}; content?:{raw?:string;rendered?:string}; excerpt?:{raw?:string;rendered?:string} };
type Action = { id:string; title:string; description:string; status:string; type:string; appliedAt?:string|null; rolledBackAt?:string|null; beforeSnapshot?:unknown; afterSnapshot?:unknown };

export function WordPressControl({ businessId, connected, baseUrl }: { businessId:string; connected:boolean; baseUrl?:string }) {
  const [isConnected,setIsConnected]=useState(connected); const [wpUrl,setWpUrl]=useState(baseUrl||""); const [username,setUsername]=useState(""); const [appPassword,setAppPassword]=useState("");
  const [items,setItems]=useState<Item[]>([]); const [type,setType]=useState<"pages"|"posts">("pages"); const [selected,setSelected]=useState<Item|null>(null);
  const [title,setTitle]=useState(""); const [content,setContent]=useState(""); const [excerpt,setExcerpt]=useState(""); const [actions,setActions]=useState<Action[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function loadItems(nextType=type){ setBusy(true); setMessage(""); try { const r=await fetch(`/api/business/${businessId}/wordpress?type=${nextType}`); const d=await r.json(); if(!r.ok) throw new Error(d.error||"Erreur WordPress"); setItems(d.items||[]); } catch(e){setMessage(e instanceof Error?e.message:"Erreur");} finally{setBusy(false);} }
  async function connect(){setBusy(true);setMessage("");try{const r=await fetch(`/api/business/${businessId}/connector`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"wordpress",baseUrl:wpUrl,username,applicationPassword:appPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Connexion impossible");setIsConnected(true);setWpUrl(d.connector.baseUrl);setMessage(`Connecté en tant que ${d.account.name||d.account.id}.`);loadItems();}catch(e){setMessage(e instanceof Error?e.message:"Connexion impossible");}finally{setBusy(false);}}
  async function selectItem(item:Item){setBusy(true);try{const r=await fetch(`/api/business/${businessId}/wordpress?type=${type}&id=${item.id}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Lecture impossible");const x=d.item as Item;setSelected(x);setTitle(x.title?.rendered||"");setContent(x.content?.raw||x.content?.rendered||"");setExcerpt(x.excerpt?.raw||x.excerpt?.rendered||"");}catch(e){setMessage(e instanceof Error?e.message:"Lecture impossible");}finally{setBusy(false);}}
  async function loadActions(){const r=await fetch(`/api/business/${businessId}/actions`);const d=await r.json();if(r.ok)setActions(d.actions||[]);}
  useEffect(()=>{ if(isConnected){loadItems();loadActions();} },[isConnected]);
  async function prepare(){if(!selected)return;setBusy(true);setMessage("");try{const r=await fetch(`/api/business/${businessId}/wordpress/actions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contentType:type,postId:selected.id,patch:{title,content,excerpt}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Impossible de préparer l'action");setMessage("Modification préparée. Rien n'est publié.");await loadActions();}catch(e){setMessage(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
  async function actionCall(id:string,verb:"apply"|"rollback"){if(!confirm(verb==="apply"?"Publier cette modification sur WordPress ?":"Restaurer la version précédente ?"))return;setBusy(true);try{const r=await fetch(`/api/actions/${id}/${verb}`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur");setMessage(verb==="apply"?"Modification publiée avec snapshot enregistré.":"Version précédente restaurée.");await loadActions();}catch(e){setMessage(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
  if(!isConnected) return <section className="panel wp-control"><div className="panel-head"><div><h2>Connecter WordPress</h2><p className="muted">Application Password recommandée. Les identifiants sont chiffrés côté serveur.</p></div><span className="badge">contrôlé</span></div><div className="wp-grid"><label>URL WordPress<input className="input" value={wpUrl} onChange={e=>setWpUrl(e.target.value)} placeholder="https://monsite.fr" /></label><label>Nom d'utilisateur<input className="input" value={username} onChange={e=>setUsername(e.target.value)} /></label><label>Application Password<input className="input" type="password" value={appPassword} onChange={e=>setAppPassword(e.target.value)} /></label></div><button className="primary" disabled={busy} onClick={connect}>{busy?"Connexion…":"Tester et connecter"}</button>{message&&<p className="small">{message}</p>}</section>;
  return <section className="panel wp-control"><div className="panel-head"><div><h2>WordPress Control Center</h2><p className="muted">{wpUrl} · aucune publication automatique</p></div><span className="badge">connecté</span></div><div className="wp-tabs"><button className={type==="pages"?"active":""} onClick={()=>{setType("pages");loadItems("pages")}}>Pages</button><button className={type==="posts"?"active":""} onClick={()=>{setType("posts");loadItems("posts")}}>Articles</button><button onClick={()=>{loadItems();loadActions()}}>Actualiser</button></div><div className="wp-editor-grid"><div><div className="wp-list">{items.map(item=><button key={item.id} className={selected?.id===item.id?"wp-item selected":"wp-item"} onClick={()=>selectItem(item)}><strong>{item.title?.rendered||`#${item.id}`}</strong><span>{item.status||"—"}</span></button>)}{!items.length&&<p className="muted">Aucun contenu trouvé.</p>}</div></div><div>{selected?<><div className="editor-note">Modification locale uniquement. Cliquez sur « Préparer » pour créer une action. La publication reste manuelle.</div><label>Titre<input className="input" value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Extrait<textarea className="input textarea" value={excerpt} onChange={e=>setExcerpt(e.target.value)} /></label><label>Contenu<textarea className="input textarea content-editor" value={content} onChange={e=>setContent(e.target.value)} /></label><div className="action-row"><button className="primary" disabled={busy} onClick={prepare}>Préparer la modification</button>{selected.link&&<a className="ghost" href={selected.link} target="_blank" rel="noreferrer">Voir le site</a>}</div></>:<div className="empty">Sélectionnez une page ou un article.</div>}</div></div><div className="wp-actions"><div className="panel-head"><h3>Actions WordPress</h3><span className="badge">{actions.length}</span></div>{actions.filter(a=>a.type==="wordpress_content").map(a=><div className="op" key={a.id}><div><strong>{a.title}</strong><p>{a.description}</p><small>{a.status}{a.appliedAt?` · publié ${new Date(a.appliedAt).toLocaleString("fr-FR")}`:""}</small></div><div className="action-buttons">{a.status==="ready"&&<button className="ghost" disabled={busy} onClick={()=>actionCall(a.id,"apply")}>Publier</button>}{a.status==="applied"&&<button className="ghost" disabled={busy} onClick={()=>actionCall(a.id,"rollback")}>Rollback</button>}</div></div>)}{!actions.filter(a=>a.type==="wordpress_content").length&&<p className="muted">Aucune modification préparée.</p>}</div>{message&&<div className="info-banner">{message}</div>}</section>;
}
