ALTER TABLE "User" ADD COLUMN "stripeSubscriptionId" TEXT;
ALTER TABLE "User" ADD COLUMN "subscriptionStatus" TEXT NOT NULL DEFAULT 'inactive';
CREATE UNIQUE INDEX "User_stripeSubscriptionId_key" ON "User"("stripeSubscriptionId");
ALTER TABLE "Business" ADD COLUMN "monitoring" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Business" ADD COLUMN "monitorEveryHours" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "Business" ADD COLUMN "nextMonitorAt" TIMESTAMP(3);
CREATE INDEX "Business_monitoring_nextMonitorAt_idx" ON "Business"("monitoring", "nextMonitorAt");
CREATE TABLE "Connector" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"type" TEXT NOT NULL,"label" TEXT NOT NULL,"baseUrl" TEXT NOT NULL,"credentialsEncrypted" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'connected',"lastCheckedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Connector_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Connector_businessId_type_key" ON "Connector"("businessId","type");
CREATE INDEX "Connector_businessId_idx" ON "Connector"("businessId");
CREATE TABLE "Action" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"opportunityId" TEXT,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'proposed',"payload" JSONB NOT NULL,"beforeSnapshot" JSONB,"afterSnapshot" JSONB,"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"appliedAt" TIMESTAMP(3),"rolledBackAt" TIMESTAMP(3),CONSTRAINT "Action_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Action_businessId_status_idx" ON "Action"("businessId","status");
CREATE INDEX "Action_businessId_createdAt_idx" ON "Action"("businessId","createdAt");
CREATE TABLE "ActionEvent" ("id" TEXT NOT NULL,"actionId" TEXT NOT NULL,"type" TEXT NOT NULL,"message" TEXT NOT NULL,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ActionEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ActionEvent_actionId_createdAt_idx" ON "ActionEvent"("actionId","createdAt");
CREATE TABLE "MonitoredQuery" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"query" TEXT NOT NULL,"provider" TEXT NOT NULL DEFAULT 'unconfigured',"active" BOOLEAN NOT NULL DEFAULT true,"lastRunAt" TIMESTAMP(3),"lastMentioned" BOOLEAN NOT NULL DEFAULT false,"lastPosition" INTEGER,"lastResponse" TEXT,"lastCitations" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "MonitoredQuery_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "MonitoredQuery_businessId_query_key" ON "MonitoredQuery"("businessId","query");
CREATE INDEX "MonitoredQuery_businessId_active_idx" ON "MonitoredQuery"("businessId","active");
CREATE TABLE "Competitor" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"name" TEXT NOT NULL,"domain" TEXT NOT NULL,"score" INTEGER,"notes" TEXT,"lastScannedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Competitor_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Competitor_businessId_domain_key" ON "Competitor"("businessId","domain");
CREATE TABLE "MonitoringRun" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'running',"previousScore" INTEGER,"newScore" INTEGER,"delta" INTEGER,"summary" TEXT,"error" TEXT,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"finishedAt" TIMESTAMP(3),CONSTRAINT "MonitoringRun_pkey" PRIMARY KEY ("id"));
CREATE INDEX "MonitoringRun_businessId_startedAt_idx" ON "MonitoringRun"("businessId","startedAt");
ALTER TABLE "Connector" ADD CONSTRAINT "Connector_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Action" ADD CONSTRAINT "Action_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Action" ADD CONSTRAINT "Action_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "Opportunity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ActionEvent" ADD CONSTRAINT "ActionEvent_actionId_fkey" FOREIGN KEY ("actionId") REFERENCES "Action"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MonitoredQuery" ADD CONSTRAINT "MonitoredQuery_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Competitor" ADD CONSTRAINT "Competitor_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MonitoringRun" ADD CONSTRAINT "MonitoringRun_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
